/** API route constants — kept in sync with backend/internal/api/router.go */
export const API_ROUTES = {
  auth: {
    login: '/api/v1/auth/login',
    logout: '/api/v1/auth/logout',
    session: '/api/v1/auth/session',
    password: '/api/v1/auth/password',
  },
  system: {
    info: '/api/v1/system/info',
    stats: '/api/v1/system/stats',
    logs: '/api/v1/system/logs',
    kernelLogs: '/api/v1/system/logs/kernel',
    reboot: '/api/v1/system/reboot',
    shutdown: '/api/v1/system/shutdown',
    hostname: '/api/v1/system/hostname',
    leds: '/api/v1/system/leds',
    ledsSchedule: '/api/v1/system/leds/schedule',
    timezone: '/api/v1/system/timezone',
    backup: '/api/v1/system/backup',
    restore: '/api/v1/system/restore',
    factoryReset: '/api/v1/system/factory-reset',
    firmwareUpgrade: '/api/v1/system/firmware/upgrade',
    ntp: '/api/v1/system/ntp',
    ntpSync: '/api/v1/system/ntp/sync',
    setupComplete: '/api/v1/system/setup-complete',
    timeSync: '/api/v1/system/time-sync',
    alerts: '/api/v1/system/alerts',
    buttons: '/api/v1/system/buttons',
    buttonActions: '/api/v1/system/button-actions',
  },
  network: {
    status: '/api/v1/network/status',
    wan: '/api/v1/network/wan',
    clients: '/api/v1/network/clients',
    clientAlias: '/api/v1/network/clients/alias',
    clientKick: '/api/v1/network/clients/kick',
    clientBlock: '/api/v1/network/clients/block',
    clientUnblock: '/api/v1/network/clients/unblock',
    clientBlocked: '/api/v1/network/clients/blocked',
    dhcp: '/api/v1/network/dhcp',
    dhcpLeases: '/api/v1/network/dhcp/leases',
    dhcpReservations: '/api/v1/network/dhcp/reservations',
    dns: '/api/v1/network/dns',
    dnsEntries: '/api/v1/network/dns/entries',
    interfaceState: '/api/v1/network/interfaces/:name/state',
    wanDetect: '/api/v1/network/wan/detect',
    ddns: '/api/v1/network/ddns',
    ddnsStatus: '/api/v1/network/ddns/status',
    uptimeLog: '/api/v1/network/uptime-log',
    dataUsage: '/api/v1/network/data-usage',
    dataUsageReset: '/api/v1/network/data-usage/reset',
    dataUsageBudget: '/api/v1/network/data-usage/budget',
    usbTethering: '/api/v1/network/usb-tethering',
    usbTetheringConfigure: '/api/v1/network/usb-tethering/configure',
    usbTetheringUnconfigure: '/api/v1/network/usb-tethering/unconfigure',
  },
  wifi: {
    scan: '/api/v1/wifi/scan',
    connect: '/api/v1/wifi/connect',
    disconnect: '/api/v1/wifi/disconnect',
    connection: '/api/v1/wifi/connection',
    mode: '/api/v1/wifi/mode',
    saved: '/api/v1/wifi/saved',
    deleteSaved: '/api/v1/wifi/saved',
    savedPriority: '/api/v1/wifi/saved/priority',
    radio: '/api/v1/wifi/radio',
    radios: '/api/v1/wifi/radios',
    radioRole: '/api/v1/wifi/radios/:name/role',
    bandSwitching: '/api/v1/wifi/band-switching',
    ap: '/api/v1/wifi/ap',
    mac: '/api/v1/wifi/mac',
    macRandomize: '/api/v1/wifi/mac/randomize',
    guest: '/api/v1/wifi/guest',
    autoreconnect: '/api/v1/wifi/autoreconnect',
    applyConfirm: '/api/v1/wifi/apply/confirm',
  },
  vpn: {
    status: '/api/v1/vpn/status',
    killswitch: '/api/v1/vpn/killswitch',
    wireguard: {
      config: '/api/v1/vpn/wireguard',
      toggle: '/api/v1/vpn/wireguard/toggle',
      import: '/api/v1/vpn/wireguard/import',
      status: '/api/v1/vpn/wireguard/status',
      profiles: '/api/v1/vpn/wireguard/profiles',
      verify: '/api/v1/vpn/wireguard/verify',
    },
    tailscale: {
      status: '/api/v1/vpn/tailscale',
      toggle: '/api/v1/vpn/tailscale/toggle',
      auth: '/api/v1/vpn/tailscale/auth',
      exitNode: '/api/v1/vpn/tailscale/exit-node',
    },
    dnsLeakTest: '/api/v1/vpn/dns-leak-test',
  },
  services: {
    list: '/api/v1/services',
    install: '/api/v1/services/:id/install',
    installStream: '/api/v1/services/:id/install/stream',
    remove: '/api/v1/services/:id/remove',
    removeStream: '/api/v1/services/:id/remove/stream',
    start: '/api/v1/services/:id/start',
    stop: '/api/v1/services/:id/stop',
    autostart: '/api/v1/services/:id/autostart',
  },
  captive: {
    status: '/api/v1/captive/status',
  },
  adguard: {
    dns: '/api/v1/adguard/dns',
    config: '/api/v1/adguard/config',
  },
} as const;
