min_version = "2024.1.0"

[tools]
  # Go toolchain
  go = "1.26.4"
  golangci-lint = "2.12.2"

  # Node.js + JS tooling
  node = "26.5.0" # or "lts" / "latest"
  #bun = "latest"
  pnpm = "11.11.0"

  # Python
  python = "3.14.6"

[settings]
  experimental = true
  jobs = 4
