package services

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/openwrt-travel-gui/backend/internal/uci"
)

func TestCaptivePortal_NoRedirect_NoPortal(t *testing.T) {
	prober := &MockHTTPProber{
		StatusCode: 204,
		Body:       "",
	}
	svc := NewCaptiveService(prober)

	status, err := svc.CheckCaptivePortal()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if status.Detected {
		t.Error("expected no captive portal detected")
	}
	if !status.CanReachInternet {
		t.Error("expected internet reachable")
	}
	if status.PortalURL != nil {
		t.Error("expected no portal URL")
	}
}

func TestCaptivePortal_Redirect_PortalDetected(t *testing.T) {
	prober := &MockHTTPProber{
		StatusCode:  302,
		Body:        "",
		RedirectURL: "http://portal.hotel.com/login",
	}
	svc := NewCaptiveService(prober)

	status, err := svc.CheckCaptivePortal()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !status.Detected {
		t.Error("expected captive portal detected")
	}
	if status.CanReachInternet {
		t.Error("expected internet NOT reachable")
	}
	if status.PortalURL == nil {
		t.Fatal("expected portal URL")
	}
	if *status.PortalURL != "http://portal.hotel.com/login" {
		t.Errorf("expected portal URL 'http://portal.hotel.com/login', got %q", *status.PortalURL)
	}
}

func TestCaptivePortal_ConnectionFailed_NoInternet(t *testing.T) {
	prober := &MockHTTPProber{
		Err: fmt.Errorf("dial tcp: connection refused"),
	}
	svc := NewCaptiveService(prober)

	status, err := svc.CheckCaptivePortal()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if status.Detected {
		t.Error("expected no captive portal detected on connection failure")
	}
	if status.CanReachInternet {
		t.Error("expected internet NOT reachable")
	}
}

func TestCaptivePortal_WrongBody_PortalDetected(t *testing.T) {
	prober := &MockHTTPProber{
		StatusCode: 200,
		Body:       "<html><body>Please login to continue</body></html>",
	}
	svc := NewCaptiveService(prober)

	status, err := svc.CheckCaptivePortal()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !status.Detected {
		t.Error("expected captive portal detected when body is wrong")
	}
	if status.CanReachInternet {
		t.Error("expected internet NOT reachable")
	}
	if status.PortalURL == nil {
		t.Fatal("expected fallback portal URL for HTTP 200 captive portal")
	}
	if *status.PortalURL != "http://connectivitycheck.gstatic.com/generate_204" {
		t.Errorf("expected probe URL as fallback, got %q", *status.PortalURL)
	}
}

func TestCaptivePortal_301Redirect(t *testing.T) {
	prober := &MockHTTPProber{
		StatusCode:  301,
		Body:        "",
		RedirectURL: "http://captive.example.com",
	}
	svc := NewCaptiveService(prober)

	status, err := svc.CheckCaptivePortal()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !status.Detected {
		t.Error("expected captive portal detected on 301")
	}
}

func TestCaptivePortal_307Redirect(t *testing.T) {
	prober := &MockHTTPProber{
		StatusCode:  307,
		Body:        "",
		RedirectURL: "http://captive.example.com",
	}
	svc := NewCaptiveService(prober)

	status, err := svc.CheckCaptivePortal()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !status.Detected {
		t.Error("expected captive portal detected on 307")
	}
}

// mockCmdRunner records calls and returns preset responses.
type mockCmdRunner struct {
	responses map[string]string
	calls     [][]string
	// blocked, when non-empty, makes every call whose key starts with it fail.
	// Tests flip it after a setup step to simulate a mid-flight failure.
	blocked string
}

func (m *mockCmdRunner) Run(name string, args ...string) ([]byte, error) {
	call := append([]string{name}, args...)
	m.calls = append(m.calls, call)
	key := name
	for _, a := range args {
		key += " " + a
	}
	if m.blocked != "" && strings.HasPrefix(key, m.blocked) {
		return nil, fmt.Errorf("blocked command: %s", key)
	}
	if resp, ok := m.responses[key]; ok {
		return []byte(resp), nil
	}
	return nil, fmt.Errorf("command not found: %s", key)
}

func newTestCaptiveServiceWithUCI(t *testing.T, prober HTTPProber, cmd *mockCmdRunner) (*CaptiveService, string) {
	u := uci.NewMockUCI()
	guardDir, _ := os.MkdirTemp("", "captive-test-*")
	guardFile := filepath.Join(guardDir, "dns-bypass-in-progress")
	svc := &CaptiveService{prober: prober, uci: u, cmd: cmd, guardFile: guardFile, stopCh: make(chan struct{})}
	// Bypass refuses to run without a DHCP-provided nameserver, so every test
	// gets a resolv.conf.auto containing one (same as a leased WAN uplink).
	svc.resolvConfAutoOverride = writeResolvAuto(t, guardDir, "10.1.2.3")
	return svc, guardDir
}

// writeResolvAuto writes a fake resolv.conf.auto with the given nameserver.
func writeResolvAuto(t *testing.T, dir, nameserver string) string {
	t.Helper()
	path := filepath.Join(dir, "resolv.conf.auto")
	if err := os.WriteFile(path, []byte("# generated by dhcp\nnameserver "+nameserver+"\n"), 0o600); err != nil {
		t.Fatalf("writing resolv.conf.auto: %v", err)
	}
	return path
}

// BypassDNS must abort when the DHCP nameserver is unknown: continuing would
// clear noresolv and drop the server list, leaving dnsmasq with no upstream.
func TestBypassDNS_AbortsWhenNoDHCPDNS(t *testing.T) {
	cmd := &mockCmdRunner{responses: map[string]string{
		"uci get dhcp.@dnsmasq[0].noresolv":          "1",
		"uci get dhcp.@dnsmasq[0].server":            "127.0.0.1#5353",
		"uci get dhcp.@dnsmasq[0].rebind_protection": "0",
	}}
	svc, dir := newTestCaptiveServiceWithUCI(t, &MockHTTPProber{StatusCode: 204}, cmd)
	defer os.RemoveAll(dir)
	// Empty nameserver file: no usable upstream can be discovered.
	svc.resolvConfAutoOverride = writeResolvAuto(t, dir, "")

	if err := svc.BypassDNS(); err == nil {
		t.Fatal("expected BypassDNS to abort without a DHCP nameserver")
	}
	if svc.IsDNSBypassed() {
		t.Error("guard file must not be created when bypass aborts")
	}
	for _, call := range cmd.calls {
		if len(call) > 1 && call[1] == "delete" {
			t.Errorf("must not touch dnsmasq server list, saw call %v", call)
		}
	}
}

// RestoreDNS must keep the guard file when a restore step fails — it is the
// only record of the pre-bypass configuration.
func TestRestoreDNS_KeepsGuardFileOnFailure(t *testing.T) {
	cmd := &mockCmdRunner{responses: map[string]string{
		"uci get dhcp.@dnsmasq[0].noresolv":             "1",
		"uci get dhcp.@dnsmasq[0].server":               "127.0.0.1#5353",
		"uci get dhcp.@dnsmasq[0].rebind_protection":    "0",
		"uci set dhcp.@dnsmasq[0].noresolv=0":           "",
		"uci delete dhcp.@dnsmasq[0].server":            "",
		"uci add_list dhcp.@dnsmasq[0].server=10.1.2.3": "",
		"uci commit dhcp":                               "",
		"/etc/init.d/dnsmasq restart":                   "",
	}}
	svc, dir := newTestCaptiveServiceWithUCI(t, &MockHTTPProber{StatusCode: 204}, cmd)
	defer os.RemoveAll(dir)
	_ = svc.uci.Set("network", "wan", "peerdns", "1")

	if err := svc.BypassDNS(); err != nil {
		t.Fatalf("BypassDNS: %v", err)
	}
	if !svc.IsDNSBypassed() {
		t.Fatal("precondition: expected active bypass")
	}
	// From here on every commit fails, so the restore cannot complete.
	cmd.blocked = "uci commit"

	err := svc.RestoreDNS()
	if err == nil {
		t.Fatal("expected RestoreDNS to report the failed commit")
	}
	if !svc.IsDNSBypassed() {
		t.Error("guard file must be kept so the restore can be retried")
	}
}

// A corrupt guard file is the only copy of the pre-bypass state: the restore
// must fail loudly instead of deleting it.
func TestRestoreDNS_CorruptGuardFileIsKept(t *testing.T) {
	svc, dir := newTestCaptiveServiceWithUCI(t, &MockHTTPProber{StatusCode: 204}, &mockCmdRunner{responses: map[string]string{}})
	defer os.RemoveAll(dir)
	if err := os.WriteFile(svc.guardFile, []byte("{not json"), 0o600); err != nil {
		t.Fatal(err)
	}

	if err := svc.RestoreDNS(); err == nil {
		t.Fatal("expected an error for an unreadable guard file")
	}
	if _, err := os.Stat(svc.guardFile); err != nil {
		t.Errorf("corrupt guard file must not be deleted: %v", err)
	}
}

// refreshBypassTimestamp races BypassDNS/RestoreDNS for the same file. It must
// take the same lock and rewrite atomically, so the file always parses.
func TestRefreshBypassTimestamp_ConcurrentWithBypassIsAtomic(t *testing.T) {
	cmd := &mockCmdRunner{responses: map[string]string{
		"uci get dhcp.@dnsmasq[0].noresolv":             "1",
		"uci get dhcp.@dnsmasq[0].server":               "127.0.0.1#5353",
		"uci get dhcp.@dnsmasq[0].rebind_protection":    "0",
		"uci set dhcp.@dnsmasq[0].noresolv=0":           "",
		"uci delete dhcp.@dnsmasq[0].server":            "",
		"uci add_list dhcp.@dnsmasq[0].server=10.1.2.3": "",
		"uci commit dhcp":                               "",
		"/etc/init.d/dnsmasq restart":                   "",
	}}
	svc, dir := newTestCaptiveServiceWithUCI(t, &MockHTTPProber{StatusCode: 204}, cmd)
	defer os.RemoveAll(dir)
	_ = svc.uci.Set("network", "wan", "peerdns", "1")

	if err := svc.BypassDNS(); err != nil {
		t.Fatalf("BypassDNS: %v", err)
	}

	// Hammer the guard file from another goroutine while refresh rewrites it.
	stop := make(chan struct{})
	done := make(chan struct{})
	go func() {
		defer close(done)
		for {
			select {
			case <-stop:
				return
			default:
			}
			data, err := os.ReadFile(svc.guardFile)
			if err != nil {
				continue
			}
			var b dnsBackup
			if err := json.Unmarshal(data, &b); err != nil {
				t.Errorf("guard file observed in a torn state: %v (content %q)", err, data)
				return
			}
		}
	}()
	for i := 0; i < 200; i++ {
		svc.refreshBypassTimestamp()
	}
	close(stop)
	<-done
}

// Stop must cancel the startup auto-restore goroutine and be idempotent.
func TestCaptiveService_StopIsIdempotentAndCancelsStartupGoroutine(t *testing.T) {
	svc := NewCaptiveServiceWithUCI(&MockHTTPProber{StatusCode: 204}, uci.NewMockUCI(), nil)
	done := make(chan struct{})
	go func() {
		svc.Stop()
		svc.Stop()
		close(done)
	}()
	select {
	case <-done:
	case <-time.After(5 * time.Second):
		t.Fatal("Stop did not return: the startup goroutine is not cancellable")
	}
}

func TestIsDNSBypassed_NoGuardFile(t *testing.T) {
	svc, dir := newTestCaptiveServiceWithUCI(t, &MockHTTPProber{StatusCode: 204}, &mockCmdRunner{responses: map[string]string{}})
	defer os.RemoveAll(dir)

	if svc.IsDNSBypassed() {
		t.Error("expected not bypassed when no guard file")
	}
}

func TestBypassDNS_CreatesGuardFile(t *testing.T) {
	cmd := &mockCmdRunner{responses: map[string]string{
		"uci get dhcp.@dnsmasq[0].noresolv":             "1",
		"uci get dhcp.@dnsmasq[0].server":               "127.0.0.1#5353",
		"uci get dhcp.@dnsmasq[0].rebind_protection":    "1",
		"uci set dhcp.@dnsmasq[0].noresolv=0":           "",
		"uci delete dhcp.@dnsmasq[0].server":            "",
		"uci add_list dhcp.@dnsmasq[0].server=10.1.2.3": "",
		"uci set dhcp.@dnsmasq[0].rebind_protection=0":  "",
		"uci commit dhcp":                               "",
		"/etc/init.d/dnsmasq restart":                   "",
	}}
	svc, dir := newTestCaptiveServiceWithUCI(t, &MockHTTPProber{StatusCode: 204}, cmd)
	defer os.RemoveAll(dir)

	err := svc.BypassDNS()
	if err != nil {
		t.Fatalf("BypassDNS error: %v", err)
	}
	if !svc.IsDNSBypassed() {
		t.Error("expected guard file to exist after bypass")
	}
}

func TestBypassDNS_NothingToBypass(t *testing.T) {
	cmd := &mockCmdRunner{responses: map[string]string{
		"uci get dhcp.@dnsmasq[0].noresolv":          "0",
		"uci get dhcp.@dnsmasq[0].server":            "",
		"uci get dhcp.@dnsmasq[0].rebind_protection": "0",
	}}
	svc, dir := newTestCaptiveServiceWithUCI(t, &MockHTTPProber{StatusCode: 204}, cmd)
	defer os.RemoveAll(dir)

	// Set wan peerdns to something that doesn't trigger bypass
	_ = svc.uci.Set("network", "wan", "peerdns", "1")

	err := svc.BypassDNS()
	if err != nil {
		t.Fatalf("BypassDNS error: %v", err)
	}
	if svc.IsDNSBypassed() {
		t.Error("should not create guard file when nothing to bypass")
	}
}

func TestRestoreDNS_RestoresAndRemovesGuard(t *testing.T) {
	cmd := &mockCmdRunner{responses: map[string]string{
		"uci get dhcp.@dnsmasq[0].noresolv":                   "1",
		"uci get dhcp.@dnsmasq[0].server":                     "127.0.0.1#5353",
		"uci get dhcp.@dnsmasq[0].rebind_protection":          "1",
		"uci set dhcp.@dnsmasq[0].noresolv=0":                 "",
		"uci delete dhcp.@dnsmasq[0].server":                  "",
		"uci add_list dhcp.@dnsmasq[0].server=10.1.2.3":       "",
		"uci set dhcp.@dnsmasq[0].rebind_protection=0":        "",
		"uci commit dhcp":                                     "",
		"/etc/init.d/dnsmasq restart":                         "",
		"uci set dhcp.@dnsmasq[0].noresolv=1":                 "",
		"uci add_list dhcp.@dnsmasq[0].server=127.0.0.1#5353": "",
		"uci set dhcp.@dnsmasq[0].rebind_protection=1":        "",
	}}
	svc, dir := newTestCaptiveServiceWithUCI(t, &MockHTTPProber{StatusCode: 204}, cmd)
	defer os.RemoveAll(dir)

	// First bypass
	if err := svc.BypassDNS(); err != nil {
		t.Fatalf("BypassDNS: %v", err)
	}
	if !svc.IsDNSBypassed() {
		t.Fatal("expected bypassed")
	}

	// Then restore
	if err := svc.RestoreDNS(); err != nil {
		t.Fatalf("RestoreDNS: %v", err)
	}
	if svc.IsDNSBypassed() {
		t.Error("expected guard file removed after restore")
	}
}

func TestRestoreDNS_NoGuardFile_Noop(t *testing.T) {
	svc, dir := newTestCaptiveServiceWithUCI(t, &MockHTTPProber{StatusCode: 204}, &mockCmdRunner{responses: map[string]string{}})
	defer os.RemoveAll(dir)

	err := svc.RestoreDNS()
	if err != nil {
		t.Fatalf("RestoreDNS should be noop when no guard file: %v", err)
	}
}

func TestCheckDNSBypassNeeded_AdGuard(t *testing.T) {
	cmd := &mockCmdRunner{responses: map[string]string{
		"uci get dhcp.@dnsmasq[0].noresolv": "1",
		"uci get dhcp.@dnsmasq[0].server":   "127.0.0.1#5353",
	}}
	svc, dir := newTestCaptiveServiceWithUCI(t, &MockHTTPProber{StatusCode: 204}, cmd)
	defer os.RemoveAll(dir)

	if !svc.CheckDNSBypassNeeded() {
		t.Error("expected bypass needed with noresolv=1 and custom server")
	}
}

func TestCheckDNSBypassNeeded_NoCustomDNS(t *testing.T) {
	cmd := &mockCmdRunner{responses: map[string]string{
		"uci get dhcp.@dnsmasq[0].noresolv": "0",
		"uci get dhcp.@dnsmasq[0].server":   "",
	}}
	svc, dir := newTestCaptiveServiceWithUCI(t, &MockHTTPProber{StatusCode: 204}, cmd)
	defer os.RemoveAll(dir)

	_ = svc.uci.Set("network", "wan", "peerdns", "1")

	if svc.CheckDNSBypassNeeded() {
		t.Error("expected no bypass needed with default DNS settings")
	}
}

func TestDetectGatewayPortalURL_NoRoute(t *testing.T) {
	cmd := &mockCmdRunner{responses: map[string]string{
		"ip route show default": "",
	}}
	svc, dir := newTestCaptiveServiceWithUCI(t, &MockHTTPProber{StatusCode: 204}, cmd)
	defer os.RemoveAll(dir)

	got := svc.detectGatewayPortalURL()
	if got != "" {
		t.Errorf("detectGatewayPortalURL with no route = %q, want empty", got)
	}
}

func TestDetectGatewayPortalURL_NoCmd(t *testing.T) {
	svc := NewCaptiveService(&MockHTTPProber{StatusCode: 204})

	got := svc.detectGatewayPortalURL()
	if got != "" {
		t.Errorf("detectGatewayPortalURL with no cmd = %q, want empty", got)
	}
}

// newMockAdGuardServer returns a test HTTP server that mimics the AdGuardHome
// /control/dns_info and /control/dns_config endpoints.
func newMockAdGuardServer(t *testing.T, upstream []string) (server *httptest.Server, receivedUpstream *[]string) {
	t.Helper()
	received := &[]string{}
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/control/dns_info":
			_ = json.NewEncoder(w).Encode(adguardDNSInfoResp{UpstreamDNS: upstream})
		case "/control/dns_config":
			var cfg adguardDNSConfig
			_ = json.NewDecoder(r.Body).Decode(&cfg)
			*received = cfg.UpstreamDNS
			w.WriteHeader(http.StatusOK)
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	return srv, received
}

func newTestCaptiveServiceWithAdGuard(t *testing.T, cmd *mockCmdRunner, agServer *httptest.Server) (*CaptiveService, string) {
	t.Helper()
	u := uci.NewMockUCI()
	guardDir, _ := os.MkdirTemp("", "captive-test-*")
	guardFile := filepath.Join(guardDir, "dns-bypass-in-progress")
	svc := &CaptiveService{prober: &MockHTTPProber{StatusCode: 204}, uci: u, cmd: cmd, guardFile: guardFile, stopCh: make(chan struct{})}
	svc.resolvConfAutoOverride = writeResolvAuto(t, guardDir, "10.1.2.3")
	if agServer != nil {
		// Patch the package-level constant via a subfield isn't possible directly,
		// so we test via the exported methods with an overridden API base.
		// We use a helper that replaces adguardAPIBase for the scope of the test.
		svc.adguardAPIBaseOverride = agServer.URL
	}
	return svc, guardDir
}

// TestBypassDNS_WithAdGuard verifies that BypassDNS patches AdGuardHome's upstream
// when AdGuardHome is present and using encrypted DNS.
func TestBypassDNS_WithAdGuard_EncryptedUpstream(t *testing.T) {
	agSrv, received := newMockAdGuardServer(t, []string{"https://dns10.quad9.net/dns-query"})
	defer agSrv.Close()

	// Write a fake resolv.conf.auto so readDHCPDNS finds a hotel DNS
	tmpResolvDir, _ := os.MkdirTemp("", "resolv-*")
	defer os.RemoveAll(tmpResolvDir)
	resolvFile := filepath.Join(tmpResolvDir, "resolv.conf.auto")
	_ = os.WriteFile(resolvFile, []byte("# test\nnameserver 10.1.2.3\n"), 0600)

	cmd := &mockCmdRunner{responses: map[string]string{
		"uci get dhcp.@dnsmasq[0].noresolv":          "0",
		"uci get dhcp.@dnsmasq[0].server":            "",
		"uci get dhcp.@dnsmasq[0].rebind_protection": "0",
	}}
	svc, dir := newTestCaptiveServiceWithAdGuard(t, cmd, agSrv)
	defer os.RemoveAll(dir)
	svc.resolvConfAutoOverride = resolvFile
	_ = svc.uci.Set("network", "wan", "peerdns", "1")

	if err := svc.BypassDNS(); err != nil {
		t.Fatalf("BypassDNS error: %v", err)
	}
	if !svc.IsDNSBypassed() {
		t.Error("expected guard file to exist after AdGuardHome-only bypass")
	}
	if len(*received) == 0 || (*received)[0] != "10.1.2.3" {
		t.Errorf("expected AdGuardHome upstream set to 10.1.2.3, got %v", *received)
	}
}

// TestBypassDNS_NoAdGuard verifies that BypassDNS still works (dnsmasq path)
// when AdGuardHome is not installed (no HTTP server at adguardAPIBase).
func TestBypassDNS_NoAdGuard_DnsmasqOnly(t *testing.T) {
	cmd := &mockCmdRunner{responses: map[string]string{
		"uci get dhcp.@dnsmasq[0].noresolv":             "1",
		"uci get dhcp.@dnsmasq[0].server":               "127.0.0.1#5353",
		"uci get dhcp.@dnsmasq[0].rebind_protection":    "0",
		"uci set dhcp.@dnsmasq[0].noresolv=0":           "",
		"uci delete dhcp.@dnsmasq[0].server":            "",
		"uci add_list dhcp.@dnsmasq[0].server=10.1.2.3": "",
		"uci commit dhcp":                               "",
		"/etc/init.d/dnsmasq restart":                   "",
	}}
	// No AdGuard server — calls to adguardAPIBase will fail with connection refused
	svc, dir := newTestCaptiveServiceWithAdGuard(t, cmd, nil)
	defer os.RemoveAll(dir)
	// Point adguardAPIBaseOverride to a non-listening address
	svc.adguardAPIBaseOverride = "http://127.0.0.1:19999"
	svc.resolvConfAutoOverride = writeResolvAuto(t, dir, "10.1.2.3")
	_ = svc.uci.Set("network", "wan", "peerdns", "1")

	if err := svc.BypassDNS(); err != nil {
		t.Fatalf("BypassDNS should succeed even without AdGuardHome: %v", err)
	}
	if !svc.IsDNSBypassed() {
		t.Error("expected guard file to exist (dnsmasq-only bypass)")
	}
}

// TestCheckDNSBypassNeeded_AdGuardEncrypted verifies that CheckDNSBypassNeeded
// returns true when AdGuardHome is running with encrypted upstreams.
func TestCheckDNSBypassNeeded_AdGuardEncrypted(t *testing.T) {
	agSrv, _ := newMockAdGuardServer(t, []string{"https://dns10.quad9.net/dns-query"})
	defer agSrv.Close()

	cmd := &mockCmdRunner{responses: map[string]string{
		"uci get dhcp.@dnsmasq[0].noresolv": "0",
		"uci get dhcp.@dnsmasq[0].server":   "",
	}}
	svc, dir := newTestCaptiveServiceWithAdGuard(t, cmd, agSrv)
	defer os.RemoveAll(dir)
	svc.adguardAPIBaseOverride = agSrv.URL
	_ = svc.uci.Set("network", "wan", "peerdns", "1")

	if !svc.CheckDNSBypassNeeded() {
		t.Error("expected bypass needed when AdGuardHome uses encrypted DNS")
	}
}

// TestCheckDNSBypassNeeded_AdGuardPlainDNS verifies bypass is not reported
// needed when AdGuardHome uses plain IP upstreams (hotel DNS already).
func TestCheckDNSBypassNeeded_AdGuardPlainDNS(t *testing.T) {
	agSrv, _ := newMockAdGuardServer(t, []string{"10.1.2.3"})
	defer agSrv.Close()

	cmd := &mockCmdRunner{responses: map[string]string{
		"uci get dhcp.@dnsmasq[0].noresolv": "0",
		"uci get dhcp.@dnsmasq[0].server":   "",
	}}
	svc, dir := newTestCaptiveServiceWithAdGuard(t, cmd, agSrv)
	defer os.RemoveAll(dir)
	svc.adguardAPIBaseOverride = agSrv.URL
	_ = svc.uci.Set("network", "wan", "peerdns", "1")

	if svc.CheckDNSBypassNeeded() {
		t.Error("expected no bypass needed when AdGuardHome already uses plain IP upstream")
	}
}

// Once the bypass is committed, the guard is the only record of the original
// dnsmasq configuration. A failure in the follow-up network writes must not
// delete it, or RestoreDNS has nothing to restore and LAN DNS stays broken.
func TestBypassDNS_KeepsGuardWhenNetworkWriteFails(t *testing.T) {
	cmd := &mockCmdRunner{responses: map[string]string{
		"uci get dhcp.@dnsmasq[0].noresolv":             "1",
		"uci get dhcp.@dnsmasq[0].server":               "127.0.0.1#5353",
		"uci get dhcp.@dnsmasq[0].rebind_protection":    "0",
		"uci set dhcp.@dnsmasq[0].noresolv=0":           "",
		"uci delete dhcp.@dnsmasq[0].server":            "",
		"uci add_list dhcp.@dnsmasq[0].server=10.1.2.3": "",
		"uci commit dhcp":                               "",
		"/etc/init.d/dnsmasq restart":                   "",
		"uci get network.wan.peerdns":                   "0",
		"uci get network.wan.dns":                       "10.1.2.3",
	}}
	svc, dir := newTestCaptiveServiceWithUCI(t, &MockHTTPProber{StatusCode: 204}, cmd)
	defer os.RemoveAll(dir)
	_ = svc.uci.Set("network", "wan", "peerdns", "0")
	// The dnsmasq bypass commits and applies before the network writes, so
	// failing this one leaves the device bypassed with the guard as the only
	// record of the original configuration.
	svc.uci = &peerdnsFailingUCI{UCI: svc.uci}

	if err := svc.BypassDNS(); err == nil {
		t.Fatal("expected the bypass to fail on the network write")
	}
	if _, err := os.Stat(svc.guardFile); err != nil {
		t.Fatalf("the crash guard must survive a failure after the bypass is committed: %v", err)
	}
}

// The AdGuard-only bypass never creates a dnsmasq `server` list, so the restore
// must tolerate `uci delete` reporting "Entry not found" instead of failing on
// every attempt (which kept the guard and IsDNSBypassed stuck true forever).
func TestRestoreDNS_ToleratesMissingServerList(t *testing.T) {
	cmd := &mockCmdRunner{responses: map[string]string{
		"uci get dhcp.@dnsmasq[0].noresolv":                   "1",
		"uci get dhcp.@dnsmasq[0].server":                     "127.0.0.1#5353",
		"uci get dhcp.@dnsmasq[0].rebind_protection":          "0",
		"uci set dhcp.@dnsmasq[0].noresolv=0":                 "",
		"uci delete dhcp.@dnsmasq[0].server":                  "",
		"uci add_list dhcp.@dnsmasq[0].server=10.1.2.3":       "",
		"uci commit dhcp":                                     "",
		"/etc/init.d/dnsmasq restart":                         "",
		"uci get network.wan.peerdns":                         "1",
		"uci set dhcp.@dnsmasq[0].noresolv=1":                 "",
		"uci set dhcp.@dnsmasq[0].rebind_protection=0":        "",
		"uci add_list dhcp.@dnsmasq[0].server=127.0.0.1#5353": "",
	}}
	svc, dir := newTestCaptiveServiceWithUCI(t, &MockHTTPProber{StatusCode: 204}, cmd)
	defer os.RemoveAll(dir)
	_ = svc.uci.Set("network", "wan", "peerdns", "1")

	if err := svc.BypassDNS(); err != nil {
		t.Fatalf("BypassDNS: %v", err)
	}

	// Make the delete report the device's real "Entry not found" failure.
	orig := svc.cmd
	svc.cmd = &missingEntryRunner{inner: orig}
	defer func() { svc.cmd = orig }()

	if err := svc.RestoreDNS(); err != nil {
		t.Fatalf("RestoreDNS must ignore a missing dnsmasq server list, got %v", err)
	}
	if svc.IsDNSBypassed() {
		t.Error("the bypass must be cleared after a successful restore")
	}
}

// missingEntryRunner makes `uci delete dhcp.@dnsmasq[0].server` fail the way a
// real device does when the option does not exist.
type missingEntryRunner struct{ inner CommandRunner }

func (m *missingEntryRunner) Run(name string, args ...string) ([]byte, error) {
	joined := strings.TrimSpace(name + " " + strings.Join(args, " "))
	if joined == "uci delete dhcp.@dnsmasq[0].server" {
		return []byte("uci: Entry not found"), fmt.Errorf("exit status 1")
	}
	return m.inner.Run(name, args...)
}

// peerdnsFailingUCI fails only the network.wan.peerdns write, so a test can
// reach the point where the dnsmasq bypass is already committed.
type peerdnsFailingUCI struct{ uci.UCI }

func (f *peerdnsFailingUCI) Set(config, section, option, value string) error {
	if config == "network" && section == "wan" && option == "peerdns" {
		return fmt.Errorf("uci set network.wan.peerdns: no such device")
	}
	return f.UCI.Set(config, section, option, value)
}
