package services

import (
	"fmt"
	"os"
	"path/filepath"
)

// wirelessToggleScriptPath is the helper invoked by the WiFi schedule cron
// entries and by the button hotplug script. It is generated (and owned) by the
// backend: writing UCI only, never `wifi up` / `wifi down`.
//
// AGENTS.md forbids scripts and SSH flows running `wifi`/`wifi up`; those
// commands are the classic ath11k/IPQ6018 driver-crash trigger. Instead the
// helper flips `wireless.*.disabled`, commits, and goes through rpcd's
// apply+confirm so a failed apply still rolls back. See ADR 0002 §6 and
// docs/architecture.md §3.
const wirelessToggleScriptPath = "/usr/libexec/travo-wireless-toggle.sh"

// wirelessToggleScript is the generated helper. `up` enables every radio,
// `down` disables every radio, replacing the old `wifi up` / `wifi down` calls.
//
// A crash guard is written before the first mutation and removed only after a
// confirmed apply, so an interrupted apply leaves an auditable marker and the
// next run refuses to touch the radios (ADR 0003).
const wirelessToggleScript = `#!/bin/sh
# Generated by travo (openwrt-travel-gui) — do not edit manually.
# Toggles every wireless device via UCI + rpcd apply/confirm.
# This script never runs "wifi up" / "wifi down".

set -u

STATE="${1:-}"
GUARD=/etc/trafo/wifi-toggle-in-progress
ROLLBACK_TIMEOUT=30

case "$STATE" in
	up)   DISABLED=0 ;;
	down) DISABLED=1 ;;
	*)    echo "usage: $0 up|down" >&2; exit 2 ;;
esac

log() { logger -t travo-wifi-toggle "$*" 2>/dev/null; }

# Refuse to run while a previous toggle is unresolved.
if [ -e "$GUARD" ]; then
	log "$GUARD present, skipping toggle"
	exit 0
fi

# Create the guard's own directory, not a hardcoded one: GUARD lives in
# /etc/trafo, and cron can fire this script before the backend has ever run, so
# the directory may not exist yet. Creating the wrong directory here made
# ": > $GUARD" fail and the toggle a silent no-op.
mkdir -p "$(dirname "$GUARD")" || exit 1
: > "$GUARD" || exit 1

fail() {
	log "toggle failed: $*"
	# Drop staged changes so the running config is never left half-applied;
	# rpcd rolls the apply back on its own when the session is not confirmed.
	uci -q revert wireless 2>/dev/null
	rm -f "$GUARD"
	exit 1
}

for dev in $(uci -q show wireless 2>/dev/null | sed -n 's/^wireless\.\(@wifi-device\[[0-9]*\]\)=wifi-device$/\1/p'); do
	uci -q set "wireless.${dev}.disabled=${DISABLED}" || fail "uci set wireless.${dev}.disabled"
done

uci -q commit wireless || fail "uci commit wireless"

APPLY_OUT=$(ubus call uci apply "{\"rollback\":true,\"timeout\":${ROLLBACK_TIMEOUT},\"uci\":\"wireless\"}" 2>/dev/null) \
	|| fail "uci apply: not available"

SESSION=$(printf '%s' "$APPLY_OUT" | jsonfilter -e '@.session' 2>/dev/null)
[ -n "$SESSION" ] || fail "rpcd returned no apply session"

ubus call uci confirm "{\"session\":\"${SESSION}\"}" >/dev/null 2>&1 || fail "uci confirm"

rm -f "$GUARD"
log "wireless toggled ${STATE} (session ${SESSION})"
exit 0
`

// writeWirelessToggleScript installs (or refreshes) the generated toggle
// helper. It is idempotent and safe to call from every configuration path that
// can schedule a toggle.
func writeWirelessToggleScript() error {
	if err := os.MkdirAll(filepath.Dir(wirelessToggleScriptPath), 0o755); err != nil {
		return fmt.Errorf("create libexec dir: %w", err)
	}
	if err := os.WriteFile(wirelessToggleScriptPath, []byte(wirelessToggleScript), 0o755); err != nil {
		return fmt.Errorf("write %s: %w", wirelessToggleScriptPath, err)
	}
	return nil
}
