package services

import (
	"fmt"
	"os"
	"path/filepath"
)

// wirelessToggleScriptPath is the helper invoked by the WiFi schedule cron
// entries and by the button hotplug script. It is generated (and owned) by the
// backend: writing UCI only, never `wifi up` / `wifi down`.
//
// AGENTS.md forbids scripts and SSH flows running `wifi`/`wifi up`; those
// commands are the classic ath11k/IPQ6018 driver-crash trigger. Instead the
// helper flips `wireless.*.disabled`, commits, and goes through rpcd's
// apply+confirm so a failed apply still rolls back. See ADR 0002 §6 and
// docs/architecture/overview.md §3.
const wirelessToggleScriptPath = "/usr/libexec/travo-wireless-toggle.sh"

// rpcdLoginHelperPath is the root-only (0600) file holding the plaintext rpcd
// login password that the generated helper below reads. It must match
// auth.RPCDLoginHelperPath for the production --auth-config-path
// (/etc/travo/auth.json); TestRPCDLoginHelperPathMatchesAuth pins that, because
// a silent mismatch here is exactly the bug this constant exists to prevent:
// the helper would fall back to an empty password, rpcd would refuse the
// login, and every scheduled or button-driven toggle would be a no-op again.
const rpcdLoginHelperPath = "/etc/travo/rpcd-login.json"

// wirelessToggleScript is the generated helper. `up` enables every radio,
// `down` disables every radio, replacing the old `wifi up` / `wifi down` calls.
//
// A crash guard is written before the first mutation and removed only after a
// confirmed apply, so an interrupted apply leaves an auditable marker and the
// next run refuses to touch the radios (ADR 0003).
//
// The sequence is: log in -> snapshot the PRE-change /etc/config/wireless -> uci
// set -> uci commit -> apply -> confirm. The snapshot must be taken before the
// commit: rpcd rolls an aborted apply back from the copy in the session dir, so
// staging the already-committed file made the rollback restore the change it was
// supposed to undo (and `uci revert`, which only drops the /tmp/.uci delta, is a
// no-op after a commit). BACKUP is the second copy, kept beside the guard, so
// fail() has a real pre-change file to put back after a commit.
const wirelessToggleScript = `#!/bin/sh
# Generated by travo (openwrt-travel-gui) — do not edit manually.
# Toggles every wireless device via UCI + rpcd apply/confirm.
# This script never runs "wifi up" / "wifi down".

set -u

STATE="${1:-}"
RPCD_RUN_DIR=/var/run/rpcd
RPCD_UCI_DIR=/etc/config
RPCD_LOGIN_ARG_FILE=` + rpcdLoginHelperPath + `
SESSION=""
APPLY_STARTED=0
GUARD=` + crashGuardDir + `/wifi-toggle-in-progress
# Pre-change copy of /etc/config/wireless, beside the guard. "uci revert" only
# drops the uncommitted delta in /tmp/.uci, so after "uci commit wireless" it
# cannot undo anything: without this file the fail() path would leave the
# committed disabled=1 in place with the radios still up, and the next unrelated
# apply would commit it silently.
BACKUP="$(dirname "$GUARD")/wifi-toggle-wireless.bak"
ROLLBACK_TIMEOUT=30

case "$STATE" in
	up)   DISABLED=0 ;;
	down) DISABLED=1 ;;
	*)    echo "usage: $0 up|down" >&2; exit 2 ;;
esac

log() { logger -t travo-wifi-toggle "$*" 2>/dev/null; }

# Refuse to run while a previous toggle is unresolved.
if [ -e "$GUARD" ]; then
	log "$GUARD present, skipping toggle"
	exit 0
fi

# Create the guard's own directory, not a hardcoded one: GUARD lives in
# /etc/trafo, and cron can fire this script before the backend has ever run, so
# the directory may not exist yet. Creating the wrong directory here made
# ": > $GUARD" fail and the toggle a silent no-op.
mkdir -p "$(dirname "$GUARD")" || exit 1
: > "$GUARD" || exit 1

cleanup_session() {
	# Only safe once the apply has NOT started. After "uci apply" succeeds,
	# rpcd reads its rollback snapshot from this session dir when its timer
	# fires; removing it first would leave the rollback with nothing to
	# restore. This mirrors RealUCIApplyConfirm.StartApply, which removes the
	# session dir only when the apply did not start.
	[ -n "$SESSION" ] && [ "$APPLY_STARTED" -eq 0 ] && rm -rf "$RPCD_RUN_DIR/uci-$SESSION"
	return 0
}

fail() {
	log "toggle failed: $*"
	# Drop staged changes so the running config is never left half-applied;
	# rpcd rolls the apply back on its own when the session is not confirmed.
	uci -q revert wireless 2>/dev/null
	# After a commit there is no delta left to revert, so put the pre-change
	# file back explicitly. Both copies are best effort: the guard is the
	# recovery marker either way.
	if [ -f "$BACKUP" ]; then
		cp "$BACKUP" "$RPCD_UCI_DIR/wireless" 2>/dev/null \
			|| log "could not restore $RPCD_UCI_DIR/wireless from $BACKUP"
	fi
	cleanup_session
	if [ "$APPLY_STARTED" -eq 1 ]; then
		# An apply is live and its rollback timer is armed. Clearing the guard
		# here would let the next cron/hotplug run start a second apply against
		# the same single apply slot while the first is still pending. Keep the
		# guard as the marker that says "unresolved", exactly as the guard
		# contract requires; the next run will skip and an operator (or a
		# deploy/reinstall, which clears guards) clears it.
		log "apply already started; leaving $GUARD in place until the rollback resolves"
	else
		rm -f "$GUARD"
	fi
	exit 1
}

# rpcd's uci apply/confirm are session-scoped: rpc_uci_apply returns
# INVALID_ARGUMENT unless the caller presents a ubus_rpc_session, and the
# rollback policy behind confirm accepts the same key. The "ubus" CLI injects no
# session of its own, so log in first and hand rpcd that session id on both
# calls. Passing a config name or a "session" key instead fails, which made this
# helper a silent no-op. Same flow as scripts/setup-wireless-ap.sh and
# RealUCIApplyConfirm in uci_apply.go.
#
# The password CANNOT be left empty. /etc/config/rpcd ships
# "option password '$p$root'", which makes rpcd verify against the real system
# root password, so an empty-password login succeeds only on a device whose
# root account has no password at all. Everywhere else the login returned no
# session and the toggle stayed a no-op -- with the radios left in whatever
# state the schedule asked them NOT to be in. The backend writes the login
# argument to a root-only file beside its seal (auth.RPCDLoginHelperPath)
# because cron and the hotplug script have no travo process to ask.
#
# The file holds the WHOLE JSON argument, already encoded, and is handed to
# ubus verbatim. Escaping the password here instead would mean reimplementing
# JSON string escaping in sed, and that is not portable: BSD sed and BusyBox
# sed disagree on 's/\\/\\\\/g', so a password containing a backslash would be
# sent differently depending on what ran this script.
LOGIN_ARG=""
[ -r "$RPCD_LOGIN_ARG_FILE" ] && LOGIN_ARG=$(cat "$RPCD_LOGIN_ARG_FILE" 2>/dev/null)
# No helper file at all: a device whose root account genuinely has no password
# still works, because rpcd then accepts an empty one.
[ -n "$LOGIN_ARG" ] || LOGIN_ARG='{"username":"root","password":""}'
LOGIN_OUT=$(ubus -S call session login "$LOGIN_ARG" 2>/dev/null) || true
SESSION=$(printf '%s' "$LOGIN_OUT" | sed -n 's/.*"ubus_rpc_session":"\([^"]*\)".*/\1/p')
[ -n "$SESSION" ] || fail "no rpcd session (checked $RPCD_LOGIN_ARG_FILE; apply via LuCI Save & Apply or reboot)"

# Snapshot the PRE-change config into the session dir, which is where rpcd
# restores from when the apply is never confirmed. This has to happen BEFORE
# "uci commit wireless": copying afterwards staged the very change the rollback
# exists to undo, so an aborted apply left disabled=1 committed while the radios
# stayed up and the next unrelated apply picked it up. BACKUP is the same
# pre-change file, kept beside the guard for the fail() path.
SESSION_DIR="$RPCD_RUN_DIR/uci-$SESSION"
mkdir -p "$SESSION_DIR" || fail "mkdir $SESSION_DIR"
cp "$RPCD_UCI_DIR/wireless" "$SESSION_DIR/wireless" || fail "stage wireless"
cp "$RPCD_UCI_DIR/wireless" "$BACKUP" || fail "back up wireless to $BACKUP"

# "uci show" prints a named section as wireless.radio0=wifi-device and an
# anonymous one as wireless.@wifi-device[0]=wifi-device. Stock OpenWrt names
# its radios, so matching only the anonymous form silently selected nothing and
# the toggle reported success without changing any radio.
for dev in $(uci -q show wireless 2>/dev/null | sed -n 's/^wireless\.\([^.=]*\)=wifi-device$/\1/p'); do
	uci -q set "wireless.${dev}.disabled=${DISABLED}" || fail "uci set wireless.${dev}.disabled"
done

uci -q commit wireless || fail "uci commit wireless"

ubus call uci apply \
	"{\"ubus_rpc_session\":\"$SESSION\",\"rollback\":true,\"timeout\":${ROLLBACK_TIMEOUT}}" \
	>/dev/null 2>&1 || fail "uci apply"

# From here on rpcd holds the rollback snapshot in the session dir and its
# timer is armed, so the session dir and the guard must both survive a later
# failure. See fail().
APPLY_STARTED=1

ubus call uci confirm "{\"ubus_rpc_session\":\"$SESSION\"}" >/dev/null 2>&1 || fail "uci confirm"

APPLY_STARTED=0
cleanup_session
rm -f "$GUARD" "$BACKUP"
log "wireless toggled ${STATE} (session ${SESSION})"
exit 0
`

// writeWirelessToggleScript installs (or refreshes) the generated toggle
// helper. It is idempotent and safe to call from every configuration path that
// can schedule a toggle.
//
// The destination is a field rather than the bare const so a test can exercise
// the callers without writing to /usr/libexec: on a non-root dev machine that
// write fails with EPERM, which is why the schedule path could not be covered
// end to end until now.
func (w *WifiService) writeWirelessToggleScript() error {
	return writeWirelessToggleScriptTo(w.toggleScriptPathOrDefault())
}

// toggleScriptPathOrDefault returns the toggle-helper destination in use.
func (w *WifiService) toggleScriptPathOrDefault() string {
	if w.toggleScriptPath != "" {
		return w.toggleScriptPath
	}
	return wirelessToggleScriptPath
}

// writeWirelessToggleScriptTo is the shared implementation behind both the
// schedule path (WifiService) and the hardware-button path (SystemService).
// An empty path means the production destination.
func writeWirelessToggleScriptTo(path string) error {
	if path == "" {
		path = wirelessToggleScriptPath
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create libexec dir: %w", err)
	}
	if err := writeGeneratedScript(path, wirelessToggleScript, 0o755); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// writeGeneratedScript installs a generated helper atomically and with the mode
// it is supposed to run under.
//
// Two defects in one: os.WriteFile truncates in place, so a power loss during the
// write leaves a half-written root-executed script that cron runs on the next
// tick; and it does NOT change the mode of an existing file, so a helper left at
// 0644 by an older build stops being executable while every check that only
// looks at its contents still passes. Writing to a sibling temp file and
// renaming fixes both: the reader sees either the old file or the whole new one,
// and the new inode always carries the requested mode.
//
// services/network_service.go has a writeFileAtomic for its own callers; it is
// not reusable from here (no shared helper module, and those are different
// files), so this is deliberately a separate small writer for the generated
// wireless scripts.
func writeGeneratedScript(path, body string, perm os.FileMode) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(body), perm); err != nil {
		return err
	}
	// WriteFile only applies perm when it CREATES the file; a leftover temp file
	// from an interrupted run must still end up with the right mode.
	if err := os.Chmod(tmp, perm); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}
